### PR TITLE
Update README.md, fix on config and Flash messages override

### PR DESCRIPTION
**Pull request by ghost**
Nice theme you've created guys. Just a simple advice for the people like me who didn't notice this at first glance.

### CODE REVIEW

**Comment by ghost** [comment]
Added the posibility to override Flash messages

**Review by maiconpinto — APPROVED** [review]
Thank you @duckmanito for your help

**Review by maiconpinto — APPROVED** [review]
Thank you @duckmanito for your help

**Review by maiconpinto — APPROVED** [review]
Thank you @duckmanito for your help

**Review by maiconpinto — APPROVED** [review]
Thank you @duckmanito for your help

**Review by maiconpinto — APPROVED** [review]
Thank you @duckmanito for your help

**Pull request merged**
